### ISSUE TITLE
plugin插件逻辑

### ISSUE THREAD

**Issue by mrme2014** [iamyours/SimpleRouter#1]
我理解了你的意思，是在编译期  通过读取jar包所有的class 文件。或者 文件夹中的class文件。

识别出标记了@Route(path = "/app/main")的类。然后通过字节码插装  补充RouteMap#的方法体

但是 plugin中存在大量的FileUtils.copyFile(jarFile, dest)  是干嘛的呢？

**Comment by iamyours** [comment]
这个dest是下一个tranform的输入数据或者最终要处理成dex的输入数据，所以要把处理后的class和jar复制到dest目录下

**Comment by mrme2014** [comment]
hi 老哥。看你也在杭州。可否加个好友？Mr_me2014 交流交流
