### ISSUE TITLE
加载Router映射错误！

### ISSUE THREAD

**Issue by Ghostbullets** [iamyours/SimpleRouter#5]
你好，为什么使用router-plugin 1.0.4不报错，1.0.1报错，请问这之间有什么区别吗？

**Comment by iamyours** [comment]
1.0.4添加了对windows环境的支持，linux(或者mac)系统于windows的文件路径格式不太一样，具体代码见[https://github.com/iamyours/SimpleRouter/commit/bdbb7367a47a7941f97f72425164ac7b582d6810](https://github.com/iamyours/SimpleRouter/commit/bdbb7367a47a7941f97f72425164ac7b582d6810)

**Comment by Ghostbullets** [comment]
没事了，断点调试后发现是因为本地module名称为:router-api  ，jarInput.name.startsWith(ROUTE_NAME)  这个判断，
ROUTE_NAME从router-api 改为:router-api 就好了
